### ISSUE TITLE
Failed to set favorite state for <image name>.

### ISSUE THREAD

**Issue by britzke** [nextcloud/recognize#536] opened 2022-12-09 17:39 UTC
### Which version of recognize are you using?

3.3.0 (former versions too)

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.2 (former versions, too)

### Which Operating system do you have installed?

ubuntu 22.10

### Which Docker container are you using to run Nextcloud? (if applicable)

no docker container

### How much RAM does your server have?

32GB

### What processor Architecture does your CPU have?

X86

### Describe the Bug

I am trying to set a new favorite for a person.

1. I select a person
2. I check one image
3. I select "Favorite" at the ... menu
4. An error message appears telling: Failed to set favorite state for (image filename).

### Expected Behavior

The selected image should be the new favorite for that person an should be shown for that person.

### To Reproduce

see above

### Debug log

I see a 404 in the javascript console of the browser with: https://<server>/remote.php/dav/Photos/2021/06/ (image filename)
 
I see nothing appropriate in the log file even with debugging set to true

**Comment by marcelklehr** [comment] 2023-01-03 13:00
This is a duplicate of https://github.com/nextcloud/photos/issues/1346

**Closed by marcelklehr** 2023-01-03 13:00 UTC
Labels: bug
