### ISSUE TITLE
cluster-faces throws error

### ISSUE THREAD

**Issue by derritter88** [nextcloud/recognize#772] opened 2023-03-25 09:10 UTC
### Which version of recognize are you using?

3.7.0

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

GPU mode

### Which Nextcloud version do you have installed?

26

### Which Operating system do you have installed?

Ubuntu 22.04

### Which Docker container are you using to run Nextcloud? (if applicable)

n/a

### How much RAM does your server have?

16

### What processor Architecture does your CPU have?

amd64

### Describe the Bug

Running `sudo -u www-data php -f ./occ recognize:cluster-faces` throws error (see debug log section).

### Expected Behavior

Run command

### To Reproduce

Command does its job.

### Debug log

Clustering face detections for user 3A60C52D-9415-4F28-A2B7-71A8CBD7A9E3
ClusterDebug: Retrieving face detections for user 3A60C52D-9415-4F28-A2B7-71A8CBD7A9E3
ClusterDebug: Found 2142 unclustered detections. Calculating clusters.
An unhandled exception has been thrown:
Error: Call to undefined method Rubix\ML\Datasets\Labeled::features() in /var/www/cloud/apps/recognize/lib/Clustering/DualTreeBall.php:107
Stack trace:
#0 /var/www/cloud/apps/recognize/lib/Clustering/MrdBallTree.php(632): OCA\Recognize\Clustering\DualTreeBall::split()
#1 /var/www/cloud/apps/recognize/lib/Clustering/MstSolver.php(22): OCA\Recognize\Clustering\MrdBallTree->grow()
#2 /var/www/cloud/apps/recognize/lib/Clustering/HDBSCAN.php(90): OCA\Recognize\Clustering\MstSolver->__construct()
#3 /var/www/cloud/apps/recognize/lib/Service/FaceClusterAnalyzer.php(79): OCA\Recognize\Clustering\HDBSCAN->__construct()
#4 /var/www/cloud/apps/recognize/lib/Command/ClusterFaces.php(64): OCA\Recognize\Service\FaceClusterAnalyzer->calculateClusters()
#5 /var/www/cloud/apps/recognize/vendor/symfony/console/Command/Command.php(298): OCA\Recognize\Command\ClusterFaces->execute()
#6 /var/www/cloud/apps/recognize/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#7 /var/www/cloud/apps/recognize/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#8 /var/www/cloud/apps/recognize/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#9 /var/www/cloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#10 /var/www/cloud/console.php(100): OC\Console\Application->run()

**Comment by derritter88** [comment] 2023-03-25 21:30
Probably linked with #766

**Comment by marcelklehr** [comment] 2023-03-30 11:54
This is a duplicate of #676

**Closed by marcelklehr** 2023-03-30 11:54 UTC
Labels: bug
