### ISSUE TITLE
Add option to only scan untagged files for recrawl

### ISSUE THREAD

**Issue by phirestalker** [nextcloud/recognize#1041] opened 2023-11-28 23:21 UTC
### Describe the feature you'd like to request

I would like a way to skip files that were already tagged when using recrawl.

### Describe the solution you'd like

Either an option in the configuration or a command line option, that causes the recrawl option to skip files that were already tagged.

### Describe alternatives you've considered

Changing the background job options to try to unstick a background job that seems to be going nowhere.

**Comment by ruedigerkupper** [comment] 2024-08-31 12:33
Duplictate of #1137 ?

**Comment by marcelklehr** [comment] 2024-09-02 06:54
Yes, this is a duplicate of #1137

Thank you for your feedback, nonetheless.

**Closed by marcelklehr** 2024-09-02 06:54 UTC
Labels: enhancement
