### ISSUE TITLE
Rename of person fails, and person disappears

### ISSUE THREAD

**Issue by luxzg** [nextcloud/recognize#777] opened 2023-03-30 15:10 UTC
### Which version of recognize are you using?

3.7.0

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

26.0.0

### Which Operating system do you have installed?

Ubuntu 22.04

### Which Docker container are you using to run Nextcloud? (if applicable)

none

### How much RAM does your server have?

16GB

### What processor Architecture does your CPU have?

x86

### Describe the Bug

I've tried to rename people in Photos app, but I got an error.
Then I've noticed one person was missing, and I sure did not hide/remove it. It was missing in both Photos and Memories.
Then I've tried renaming another person in Memories app, and again the error. But I've immediately noticed person was also gone from the list!

Thus I'm currently believing that when I rename a person, some error happens, and person gets deleted (or becomes bugged and hidden)

### Expected Behavior

Rename of person should work and just rename a person.

### To Reproduce

NC 26
Recognize 3.7.0
Photos 2.2.0
Memories 4.12.5

Start generating face index. When you get some faces click on a thumbnail. Either in Photos or in Memories apps pick option to rename a person. If person's "name" is currently "14" rename it to something like "14Luka" and try to save. Error happens. Person's thumbnail is gone from the list.

### Debug log

(incoming)

**Comment by marcelklehr** [comment] 2023-06-05 11:52
Can you try this again with the latest version?

**Comment by Hainer1** [comment] 2023-06-12 06:02
I merge, rename and have the same problem. After some time the person's folder was gone. I did not delete the folder.
The Folder did not come back even after 24 hours.
My current system:
NC 26.0.2
Recognize 4.1.0

**Comment by marcelklehr** [comment] 2023-06-21 09:43
I'm sorry to say, I cannot reproduce this. Did you use any special characters in your names?

**Comment by Hainer1** [comment] 2023-06-21 15:09
Recognised people only have a first name with standard characters. My username on NC has a space in it, which is not ideal.

**Comment by lbckmnn** [comment] 2023-10-16 20:47
I can reproduce this by assigning two persons the same name.

**Comment by daxcore** [comment] 2024-01-14 18:50
Same here. Used a name string a second time, now the first person is gone.

**Comment by marcelklehr** [comment] 2024-05-08 10:48
Fixed in the latest version.

**Closed by marcelklehr** 2024-05-08 10:48 UTC
Labels: bug
