### ISSUE TITLE
Ability to select thumbnail of Person manually, face score or most recent image

### ISSUE THREAD

**Issue by Andreaux** [nextcloud/recognize#825] opened 2023-05-02 01:26 UTC
### Describe the feature you'd like to request

Thumbnails (faces) of people in People seem to be selected randomly. It would be nice to be able to override the default selection with:
- manual selection of one of the faces in the cluster
- automatic selection based on face score
- automatic selection based on most recent image

### Describe the solution you'd like

Option(s) in the Persons 3-dot menu if a picture is selected to:
- Assign selected face as thumbnail for this person

Option(s) in the Persons 3-dot menu if no picture is selected to:
- Automatically choose face thumbnail based on score
- Automatically choose most recent image as face thumbnail

### Describe alternatives you've considered

Not really sure what to write here...

**Comment by marcelklehr** [comment] 2024-10-10 10:36
This is a duplicate of #640

**Closed by marcelklehr** 2024-10-10 10:36 UTC
Labels: enhancement
