### ISSUE TITLE
Recognize slows the machine down, almost freezes

### ISSUE THREAD

**Issue by GHBLoos** [nextcloud/recognize#519] opened 2022-11-28 19:44 UTC
**Describe the bug**
Server extremely slow. At some point the server doesn't respond at all. The cause seems related to recognize, because it start when enabling the app and ends when stopping the app.

The server response slow and the behaviour is irregular. 

When clicking on people (/index.php/apps/photos/faces), it takes minutes before the page is fully loaded. If you simultaniously open another page from the nextcloud server, that also loads slow.

In the log file there is a warning (recognize) and error (core) at the same time. The warning is related to memory. The core error is related to cron job and recognize.  The combination of warning and error comes up several times with different time intervals. I am not sure that the warnings and errors are related to the behaviour, because the timing is difficult to check (when the behaviour starts, I hardly can check the logs).

**To Reproduce**
1. Start the app recognize
2. Wait . Behaviour (slow server responses) starts after a while, and it can sometimes be gone for a while.
3. Stop the app recognize
4. The behaviour stops

**Expected behavior**
Normal speed of the server

**Recognize (please complete the following information):**
 - Installed app version: [3.2.3]
 - WASM mode: [No]
 - Enabled modes: [all]
 - 1 core

**Server (please complete the following information):**
 - Nextcloud version: [25.0.1]
 - OS: Linux 4.18.0-372.19.1.el8_6.x86_64 x86_64
  - RAM: 5.61 GB
 - Processor Architecture AMD EPYC Processor (with IBPB) (4 cores)

**Additional context**
![image](https://user-images.githubusercontent.com/16174035/204364004-a8ed72b4-4231-42d8-bb8f-a9ef44935e40.png)

*Warning*
[recognize] Waarschuwing: Classifier process output: 2022-11-27 16:25:12.367888: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-27 16:25:38.701492: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 16777216 exceeds 10% of free system memory.
2022-11-27 16:25:38.786925: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 16777216 exceeds 10% of free system memory.
2022-11-27 16:25:38.790791: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 16777216 exceeds 10% of free system memory.
2022-11-27 16:25:38.803248: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 16777216 exceeds 10% of free system memory.
2022-11-27 16:25:38.860278: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 16777216 exceeds 10% of free system memory.

at 2022-11-27T15:43:00+00:00

Warnings can be different, but seem comparable

*Error*
[core] Fout: RuntimeException: Classifier process error at <<closure>>

0. /var/www/cloud.gaston.nl/html/apps/recognize/lib/Classifiers/Images/ImagenetClassifier.php line 47
   OCA\Recognize\Classifiers\Classifier->classifyFiles()
1. /var/www/cloud.gaston.nl/html/apps/recognize/lib/BackgroundJobs/ClassifyImagenetJob.php line 41
   OCA\Recognize\Classifiers\Images\ImagenetClassifier->classify()
2. /var/www/cloud.gaston.nl/html/apps/recognize/lib/BackgroundJobs/ClassifierJob.php line 70
   OCA\Recognize\BackgroundJobs\ClassifyImagenetJob->classify()
3. /var/www/cloud.gaston.nl/html/apps/recognize/lib/BackgroundJobs/ClassifyImagenetJob.php line 33
   OCA\Recognize\BackgroundJobs\ClassifierJob->runClassifier()
4. /var/www/cloud.gaston.nl/html/lib/public/BackgroundJob/Job.php line 78
   OCA\Recognize\BackgroundJobs\ClassifyImagenetJob->run()
5. /var/www/cloud.gaston.nl/html/lib/public/BackgroundJob/TimedJob.php line 103
   OCP\BackgroundJob\Job->start()
6. /var/www/cloud.gaston.nl/html/lib/public/BackgroundJob/TimedJob.php line 93
   OCP\BackgroundJob\TimedJob->start()
7. /var/www/cloud.gaston.nl/html/cron.php line 152
   OCP\BackgroundJob\TimedJob->execute()

at 2022-11-27T15:43:00+00:00

I will change this issue when I have better info.

**Comment by clesmian** [comment] 2022-12-06 11:05
For me it seems the biggest issue is concerning the database queries. My nextcloud works fine overall, but as soon as I open `/index.php/apps/photos/faces` or `/index.php/apps/photos/tags` the load drastically increases. 

Looking at htop, my mysql daemon consumes almost all of the resources and `SHOW PROCESSLIST;` returns more than 100 rows. Out of these rows all but three come from nextcloud

My log files do not contain any messages related to this issue

**Comment by Forza-tng** [comment] 2022-12-12 18:15
> When clicking on people (/index.php/apps/photos/faces), it takes minutes before the page is fully loaded. If you simultaniously open another page from the nextcloud server, that also loads slow.

Looks like photos app creates  lots (thousands) of sql requests and I think this partly the cause. Possibly also actually loading of all tagged images is a problem.

**Comment by GHBLoos** [comment] 2022-12-18 16:24
@marcelklehr : thanks for your reply. I wanted to give an update on what my experience is, but at this moment there are so many remarks to make, that I think something is messed up to much to give any good feedback. Maybe I should uninstall and install the app again. But before installing, maybe it is best to remove the related data. What is the best way to do that?

**Comment by rusitschka** [comment] 2022-12-23 22:04
I've been using https://apps.nextcloud.com/apps/facerecognition for a while and never experienced any of these issues. I switched to recognize because integration to Nextcloud seems to be more intuitive. It is but it currently cannot cope with the 40k images I have.

**Comment by rusitschka** [comment] 2022-12-23 22:17
Regarding clustering https://apps.nextcloud.com/apps/facerecognition is also much more advanced. Can you integrate the AI of `facerecognition` into `recognize` UI?

**Comment by marcelklehr** [comment] 2022-12-30 16:35
I believe this is a duplicate of #335

**Closed by marcelklehr** 2022-12-30 16:35 UTC
