### ISSUE TITLE
.nomedia seems to be ignored

### ISSUE THREAD

**Issue by Ellpeck** [nextcloud/recognize#389] opened 2022-10-16 18:16 UTC
**Describe the bug**
In previous versions of Recognize, any files and directories whose parent directories contain a `.nomedia` or `.noimage` file weren't processed by Recognize. However, ever since version 3 of Recognize, this feature seems to be missing. 

I briefly checked the repository and it seems that the only file that was referencing `.nomedia` and `.noimage` don't exist anymore in the current versions, though I don't understand the codebase well enough to know if this actually means that they're not being queried anymore.

*Note: This issue was already briefly mentioned in #337, but that issue is mainly about a feature request so I thought it would make the most sense to open a proper report for this issue.*

**To Reproduce**
1. Add a `.nomedia` file to a directory containing images, or which has a subdirectory containing images
2. Install Recognize

**Expected behavior**
The directory containing the `.nomedia` file is ignored for recognition, including all of the images in it and all of the images in all of its subdirectories.

**Recognize (please complete the following information):**
 - JS-only mode: No
 - Enabled modes: Object detection, though this also seems to occur with the other modes

**Server (please complete the following information):**
 - Nextcloud: 25.0.0 RC5
 - OS: Ubuntu Server 18.04
 - RAM: 12GB
 - Processor Architecture: x86

**Comment by Haschtl** [comment] 2022-10-20 19:43
I can confirm this behavior. 
I have faces recognized from e.g. album covers, which are excluded from my Photos with .noimage and .nomedia. 
But when I click on a face, I see no pictures - obviously because they are excluded.
Same server setup as you, only OS is Ubuntu 20.04

**Comment by elpraga** [comment] 2022-10-27 00:13
Same here

**Comment by marcelklehr** [comment] 2022-11-08 12:29
Fixed by #468

**Closed by marcelklehr** 2022-11-08 12:29 UTC
Labels: enhancement
