### ISSUE TITLE
Unassigned faces have up to 9 of each image with the same square drawn

### ISSUE THREAD

**Issue by prurigro** [nextcloud/recognize#923] opened 2023-07-27 04:53 UTC
### Which version of recognize are you using?

4.3.0

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

26.0.2

### Which Operating system do you have installed?

Archlinux

### Which Docker container are you using to run Nextcloud? (if applicable)

n/a

### How much RAM does your server have?

64GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

In the unassigned faces section, each image is present up to 9 times for each person. Images with a bunch of people will have 30+ copies, with each of the people highlighted a bunch of times. You can't select the same image twice when assigning a particular person, so to clear them you need to select one of the photos, choose the person, select the next photo, choose the same person, etc.

### Expected Behavior

Recognize would notice that the same image has the same square in the same spot more than once and drop the duplicates.

### To Reproduce

I'm not sure how to reproduce, but I only just installed it recognize today. I don't want to blow away my database because I've manually corrected hundreds of incorrect faces already.

### Debug log

I'm not sure how useful this would be at this point, but I can enable it and run a particular operation if it's helpful.

Thanks!

**Comment by phil-lipp** [comment] 2023-07-27 11:47
Same here, although I don't think the duplicates show up 9 times, but only about 4-6 times.

**Comment by neilsjefferies** [comment] 2023-08-02 07:44
Also have it here. I think a duplicate appears every time an image is shared. It looks like the filter for displaying Unassigned Faces doesn't handle users properly. Or maybe it's the way Unassigned faces is populated in the first place.

**Comment by marcelklehr** [comment] 2023-08-05 13:07
Are there also duplicates for assigned faces? Would be interesting for both before and after assigning unassigned duplicates.

**Comment by neilsjefferies** [comment] 2023-08-05 13:36
Assigned faces are fine - they seem to work per user. But the unassigned faces are visible to all users and contain the duplicates. Interestingly, you can take each of the duplicates and assign them to same person and they all then appear under that person (for the user that assigned them).

**Comment by marcelklehr** [comment] 2023-08-05 13:55
> But the unassigned faces are visible to all users 

How do you draw that conclusion? Do you see photos there that you cannot see in the normal photos views?

**Comment by neilsjefferies** [comment] 2023-08-05 14:22
If I log on as a different user who I have shared pictures with, and add the shared folder to their memories then they see their assigned faces (with just ID's since they haven't named them), but in unassigned faces they also see all the duplicates.

**Comment by marcelklehr** [comment] 2023-08-15 08:42
Does the number of duplicates reflect the number of faces in the photo? That's would be expected as each face can be assigned to a different person. If the people all have the same square, maybe it's a bug in memories? I will test more

**Comment by marcelklehr** [comment] 2023-08-15 08:50
Tested and the duplicates are a memories bug. Not reproducible in the photos app.

**Closed by marcelklehr** 2023-08-15 08:50 UTC
Labels: bug

**Comment by prurigro** [comment] 2023-08-15 20:05
Thanks for looking into this @marcelklehr - I couldn't actually find a way to assign unassigned faces in the Photos app to compare. Is it somewhere other than the "People" category?

**Comment by marcelklehr** [comment] 2023-08-15 20:10
It's still unreleased in the photos app, will likely come with 28 ;)
