### ISSUE TITLE
Recognize hogs more resources than configured, taking down the machine

### ISSUE THREAD

**Issue by gohrner** [nextcloud/recognize#596] opened 2022-12-30 16:06 UTC
### Which version of recognize are you using?

3.3.4

### Enabled Modes

Object recognition, Face recognition, Video recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.2

### Which Operating system do you have installed?

Debian 11 "Bullseye"

### Which Docker container are you using to run Nextcloud? (if applicable)

--

### How much RAM does your server have?

4 GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Recognize started so many node processes occupying so much memory that the server was basically down for the night with a load of > 50, before I managed to intervene and kill the node processes.

I then reconfigured regonize to use only 1 CPU. However, it still started 4 or 5 node processes again, using more than 6 GB swap before I killed the processes again.

I disabled the regonize app in the settings page, but again after a while a node process started to show up and I had to kill it.

### Expected Behavior

With a CPU setting of "1", I'd have expected at most one node process, which might be acceptable to keep the server going while the classification is running.

Maybe have a look at how the Nextcloud faceregonition app does it - the results seem to be much better and the system load much lower...

### To Reproduce

Just enable the recognize app on a machine with about 4 GB of RAM and about 16 GB swap space on a slower disk, which also has other server processes running.

There were a few thousand digicam images on the instance, and about 20 or 30 videos (only).

The system will come to a halt once classification really started running, even with only 1 CPU configured on the settings page.

**Comment by marcelklehr** [comment] 2022-12-30 16:35
I believe this is a duplicate of #335

**Closed by marcelklehr** 2022-12-30 16:35 UTC
Labels: bug

**Comment by gohrner** [comment] 2022-12-30 22:08
Sounds like. Sorry, seem to have missed the original report.
