### ISSUE TITLE
Error during the installation of the APP 

### ISSUE THREAD

**Issue by MANFahrer-GF** [nextcloud/recognize#730] opened 2023-03-12 07:09 UTC
### Which version of recognize are you using?

3.6.2

### Enabled Modes

Object recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.4.1

### Which Operating system do you have installed?

Ubuntu 22.04

### Which Docker container are you using to run Nextcloud? (if applicable)

23.0.1

### How much RAM does your server have?

8GB

### What processor Architecture does your CPU have?

AMD // AMD EPYC Processor (4 cores)

### Describe the Bug

The following error occurs during the installation: `Could not extract app recognize: Unable to extract symbolic link {/mnt/ncdata/tmp/oc_tmp_jAoAnJ-folder/recognize/node_modules/@mapbox/node-pre-gyp/node_modules/.bin/rimraf}
`
Both via the interface and the command line

### Expected Behavior

The installation should go through without errors

### To Reproduce

without

### Debug log

Exception: Could not extract app recognize: Unable to extract symbolic link {/mnt/ncdata/tmp/oc_tmp_jAoAnJ-folder/recognize/node_modules/@mapbox/node-pre-gyp/node_modules/.bin/rimraf}

**Comment by szaimen** [comment] 2023-03-13 12:02
This reminds me of https://github.com/nextcloud/recognize/issues/698

**Comment by marcelklehr** [comment] 2023-03-19 16:32
Closing as duplicate of #698

**Closed by marcelklehr** 2023-03-19 16:32 UTC
Labels: bug
