### ISSUE TITLE
n.faceDetections.find(...) is undefined

### ISSUE THREAD

**Issue by SKB-CGN** [nextcloud/recognize#521] opened 2022-11-30 10:09 UTC
Most of the time, this erros occurs, after combining one peron with another one an repeating this with the next person.
![2022-11-30 11_08_41-Fotos - Kreyenborg koeln - Cloud — Mozilla Firefox](https://user-images.githubusercontent.com/58603329/204768176-41709cd9-cfd7-4cf7-ba5d-6193ff81cf17.png)

**Comment by marcelklehr** [comment] 2022-11-30 11:18
Hey @SKB-CGN 

I believe this is fixed in the latest photos app code, which will be released as part of v25.0.2 soon

**Comment by SKB-CGN** [comment] 2022-11-30 11:20
Hi,
Thanks for letting me know.

Is it possible, to get a "fixed" one nearly now as I am trying to base order my faces currently.

Thank you!

**Comment by marcelklehr** [comment] 2022-11-30 11:32
You can install the RC of v25.0.2 if you want to have the fix now :)

**Comment by SKB-CGN** [comment] 2022-11-30 12:10
Thanks. Will do ;)

**Comment by SKB-CGN** [comment] 2022-11-30 14:00
Installed RC 25.0.2 and the problem occurs after the 3rd person. Not after the second one as before.

![2022-11-30 14_59_39-Fotos - Kreyenborg koeln - Cloud — Mozilla Firefox](https://user-images.githubusercontent.com/58603329/204815622-1a76e608-e823-4020-909c-505761b753a3.png)

**Comment by SKB-CGN** [comment] 2022-12-09 21:30
Installed official Version of 25.0.2 and the problem is still there.

This is very annoying, if you only able to add or modify 1 person and need to reload the complete page, which has 60MB of mini pictures.

**Comment by marcelklehr** [comment] 2022-12-10 18:15
mmmh

**Comment by SKB-CGN** [comment] 2022-12-10 18:36
> mmmh

Indeed 😉

**Comment by SKB-CGN** [comment] 2022-12-15 08:14
I think, i stepped forward. Just noticed, that this error is throwing everytime, when i enter a "face", which has only 1 face inside it, which i want to transfer to an other person. If i have more than 1 picture inside the "face", its working. Could you investigate that?

**Comment by timedin-de** [comment] 2022-12-22 14:15
Issue still persits.
For me also with adding 2 Images to a larger Person.

But it works for me when adding a (large) Person-Folder to the Folder with few (also just one) images, only drawback is that the specified name will reset.

**Comment by SKB-CGN** [comment] 2022-12-22 14:18
I have switched to the other Face Recognition App, which does not have the problem and even provides ignoring people.

**Comment by timedin-de** [comment] 2022-12-22 14:21
this one? https://apps.nextcloud.com/apps/facerecognition

Already tried that before but had dependency problems, but thanks, i'll try that again.

**Comment by SKB-CGN** [comment] 2022-12-22 14:22
Yes, correct. It's a bit tricky, to get it working as you need to compile some files by your own but that's worth the time :-)

**Comment by marcelklehr** [comment] 2023-01-03 13:12
I can confirm the issue is fixed in the latest commit on the main branch.

**Closed by marcelklehr** 2023-01-03 13:12 UTC
