### ISSUE TITLE
Blank faces

### ISSUE THREAD

**Issue by DenuxPlays** [nextcloud/recognize#799] opened 2023-04-10 17:50 UTC
### Which version of recognize are you using?

3.7.0

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.5

### Which Operating system do you have installed?

Fedora 37

### Which Docker container are you using to run Nextcloud? (if applicable)

23.0.3

### How much RAM does your server have?

8GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

10 out of my 14 faces are just blank. With no pictures, profile picture or name...

![image](https://user-images.githubusercontent.com/83671398/230960502-8344492e-2c8a-4ccf-8e2c-d3c9022d90d3.png)

And this is how it looks when you click on a blank person

![image](https://user-images.githubusercontent.com/83671398/230960751-f8a2b7f1-649d-4101-b7ac-f1a78505b639.png)

Also no errors, warnings etc can be found in the log file.

### Expected Behavior

Correctly displaying all the faces.

### To Reproduce

1. Install recognize
2. let it scan a whole bunch of pictures (in my case  round about 3.700)
3. take a look at the pictures

### Debug log

Nothing

**Comment by SaschaWeisenberger** [comment] 2023-04-26 06:48
+1, nextcloud 26.0.1 (in docker) and Recognize 3.7.0. Exactly the same behavior.

There is something in the log that might help:
<details>
<summary>Text</summary>
[webdav] Fehler: BadFunctionCallException: metadata is not a valid attribute at <<closure>>

 0. /var/www/html/lib/public/AppFramework/Db/Entity.php line 169
    OCP\AppFramework\Db\Entity->getter("metadata")
 1. /var/www/html/custom_apps/recognize/lib/Dav/Faces/FacePhoto.php line 148
    OCP\AppFramework\Db\Entity->__call("getMetadata", [])
 2. /var/www/html/custom_apps/recognize/lib/Dav/Faces/PropFindPlugin.php line 57
    OCA\Recognize\Dav\Faces\FacePhoto->getMetadata()
 3. /var/www/html/3rdparty/sabre/dav/lib/DAV/PropFind.php line 95
    OCA\Recognize\Dav\Faces\PropFindPlugin->OCA\Recognize\Dav\Faces\{closure}("*** sensitive parameters replaced ***")
 4. /var/www/html/custom_apps/recognize/lib/Dav/Faces/PropFindPlugin.php line 57
    Sabre\DAV\PropFind->handle("{http://nextclo ... e", ["Closure"])
 5. /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    OCA\Recognize\Dav\Faces\PropFindPlugin->propFind(["Sabre\\DAV\\PropFind"], ["OCA\\Recognize\\Dav\\Faces\\FacePhoto"])
 6. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 1052
    Sabre\DAV\Server->emit("propFind", [["Sabre\\DAV\\P ... ]])
 7. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 984
    Sabre\DAV\Server->getPropertiesByNode(["Sabre\\DAV\\PropFind"], ["OCA\\Recognize\\Dav\\Faces\\FacePhoto"])
 8. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 1662
    Sabre\DAV\Server->getPropertiesIteratorForPath("recognize/Sascha/faces/50", ["{DAV:}getconte ... "], 1)
 9. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 1647
    Sabre\DAV\Server->writeMultiStatus(["Sabre\\Xml\\Wr ... ]], ["Generator"], false)
10. /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 346
    Sabre\DAV\Server->generateMultiStatus(["Generator"], false)
11. /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPropFind(["Sabre\\HTTP\\Request"], ["Sabre\\HTTP\\Response"])
12. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit("method:PROPFIND", [["Sabre\\HTTP\\ ... ]])
13. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod(["Sabre\\HTTP\\Request"], ["Sabre\\HTTP\\Response"])
14. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
15. /var/www/html/apps/dav/lib/Server.php line 366
    Sabre\DAV\Server->exec()
16. /var/www/html/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
17. /var/www/html/remote.php line 172
    require_once("/var/www/html/a ... p")

PROPFIND /remote.php/dav/recognize/Sascha/faces/50/
from 172.20.0.1 by Sascha at 2023-04-26T06:40:29+00:00
</details>

**Comment by marcelklehr** [comment] 2023-04-26 13:21
This seems to be a duplicate of #806. Hence, I'm closing this for now. Feel free to comment here if you believe this is a mistake.

**Closed by marcelklehr** 2023-04-26 13:21 UTC
Labels: bug

**Comment by SaschaWeisenberger** [comment] 2023-04-30 11:07
Installed 4.0.1 but still the same behaviour. I reset all the tags and rescanned all images, but no luck.
