### ISSUE TITLE
Cron stops working in NC 26

### ISSUE THREAD

**Issue by enoch85** [nextcloud/recognize#766] opened 2023-03-24 08:31 UTC
### Which version of recognize are you using?

3.7.0

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

26.0.0

### Which Operating system do you have installed?

Ubuntu 22.04 Server

### Which Docker container are you using to run Nextcloud? (if applicable)

N/A

### How much RAM does your server have?

8 GB

### What processor Architecture does your CPU have?

X86_64

### Describe the Bug

When Recognize are active, it stops cron from working. Running the cron job manually results in this stracktrace:

```
Error: Call to undefined method Rubix\ML\Datasets\Labeled::features() in /var/www/nextcloud/apps/recognize/lib/Clustering/DualTreeBall.php:107
Stack trace:
#0 /var/www/nextcloud/apps/recognize/lib/Clustering/MrdBallTree.php(632): OCA\Recognize\Clustering\DualTreeBall::split()
#1 /var/www/nextcloud/apps/recognize/lib/Clustering/MstSolver.php(22): OCA\Recognize\Clustering\MrdBallTree->grow()
#2 /var/www/nextcloud/apps/recognize/lib/Clustering/HDBSCAN.php(90): OCA\Recognize\Clustering\MstSolver->__construct()
#3 /var/www/nextcloud/apps/recognize/lib/Service/FaceClusterAnalyzer.php(79): OCA\Recognize\Clustering\HDBSCAN->__construct()
#4 /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClusterFacesJob.php(39): OCA\Recognize\Service\FaceClusterAnalyzer->calculateClusters()
#5 /var/www/nextcloud/lib/public/BackgroundJob/Job.php(78): OCA\Recognize\BackgroundJobs\ClusterFacesJob->run()
#6 /var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php(57): OCP\BackgroundJob\Job->start()
#7 /var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php(47): OCP\BackgroundJob\QueuedJob->start()
#8 /var/www/nextcloud/cron.php(152): OCP\BackgroundJob\QueuedJob->execute()
#9 {main}
```

### Expected Behavior

Cron should work with recognize enabled

### To Reproduce

Install/update to NC 26
Enable Recognize
Notice cron stops working

**Comment by marcelklehr** [comment] 2023-03-30 11:55
This is a duplicate of https://github.com/nextcloud/recognize/issues/676

**Closed by marcelklehr** 2023-03-30 11:55 UTC
Labels: bug
