### ISSUE TITLE
Classifier process error

### ISSUE THREAD

**Issue by adrianog91** [nextcloud/recognize#419] opened 2022-10-24 13:58 UTC
**Describe the bug**
Error during first attempt to recognize. At the first attempt to recognize, after having processed about 300 photos on the "Recognize" section of the admin settings it is displayed that an error has occurred and to check the logs.

**To Reproduce**
1. Go to Administration settings
2. Click on Recognize
3. See error

**Expected behavior**
It should show that for face recognition, face recognition is working correctly

**Recognize (please complete the following information):**
 - JS-only mode: Yes
 - Enabled modes: face recognition

**Server (please complete the following information):**
 - Nextcloud: [25.0.0]
 - OS: [Rasbian 64 bit]
 - RAM: [4GB]
 - Processor Architecture [ ARMV8 64 bit]

**Additional context**
This are the logs;

`[recognize] Warning: Classifier process output: Aborted()
/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6599
                    throw ex;
                    ^

RuntimeError: Aborted(). Build with -s ASSERTIONS=1 for more info.
    at abort (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6795:135)
    at _abort (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6870:33)
    at <anonymous>:wasm-function[11]:0x1097
    at ResizeBilinear (<anonymous>:wasm-function[134]:0xc3f0)
    at Module._ResizeBilinear (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6979:124)
    at Object.resizeBilinear [as kernelFunc] (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:3956:5)
    at kernelFunc (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4591:32)
    at /var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4651:27
    at Engine.scopedRun (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4456:23)
    at Engine.runKernelFunc (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4647:14)

at 2022-10-24T13:40:17+00:00`

**Comment by jakobroehrl** [comment] 2022-10-26 07:13
Same as https://github.com/nextcloud/recognize/issues/370

**Comment by adrianog91** [comment] 2022-10-31 22:08
@jakobroehrl I confirm you have found the problem with my face recognition interruptions. The problem occurs when the system tries to perform face recognition on a "panoramic" photo. If I delete the "panaromic" photo, (with a large grad angle) the facecognition system starts working again and with the processor the photos in the queue. If you need to replicate the problem, I can send you these photos privately.

**Comment by marcelklehr** [comment] 2022-11-03 18:31
> If I delete the "panaromic" photo, (with a large grad angle) the facecognition system starts working again 

What is your recognize version? Have you tried updating to the latest?

**Comment by marcelklehr** [comment] 2022-11-03 18:32
@jakobroehrl not sure it's the same bug, tbh, on your bug you have a different error message (or rather, none at all), right?

**Comment by karpiq24** [comment] 2022-11-04 09:08
After upgrading to Nextcloud 25.0.1 and Recognize 3.1.2 everything worked fine for a few hours, photos where getting tagged and faces recognized, but now I'm getting "Classifier process error" aswell. I can't pinpoint exact photo causing problem as I have hundreds of GBs stored on nextcloud. (Over 200k photos in queue currently).
```

[core] Error: RuntimeException: Classifier process error at <<closure>>

0. /config/www/nextcloud/apps/recognize/lib/Classifiers/Images/LandmarksClassifier.php line 45
   OCA\Recognize\Classifiers\Classifier->classifyFiles()
1. /config/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyLandmarksJob.php line 39
   OCA\Recognize\Classifiers\Images\LandmarksClassifier->classify()
2. /config/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifierJob.php line 67
   OCA\Recognize\BackgroundJobs\ClassifyLandmarksJob->classify()
3. /config/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyLandmarksJob.php line 31
   OCA\Recognize\BackgroundJobs\ClassifierJob->runClassifier()
4. /config/www/nextcloud/lib/public/BackgroundJob/Job.php line 78
   OCA\Recognize\BackgroundJobs\ClassifyLandmarksJob->run()
5. /config/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 103
   OCP\BackgroundJob\Job->start()
6. /config/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 93
   OCP\BackgroundJob\TimedJob->start()
7. /config/www/nextcloud/cron.php line 152
   OCP\BackgroundJob\TimedJob->execute()

at 2022-11-04T08:46:32+00:00

```
```

{
  "reqId": "QOVsoCC7JV5FZoUkc6le",
  "level": 3,
  "time": "2022-11-04T08:46:32+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "core",
  "method": "",
  "url": "--",
  "message": "Error while running background job (class: OCA\\Recognize\\BackgroundJobs\\ClassifyLandmarksJob, arguments: Array\n(\n    [storageId] => 1\n    [rootId] => 39166\n)\n)",
  "userAgent": "--",
  "version": "25.0.1.1",
  "exception": {
    "Exception": "RuntimeException",
    "Message": "Classifier process error",
    "Code": 0,
    "Trace": [
      {
        "file": "/config/www/nextcloud/apps/recognize/lib/Classifiers/Images/LandmarksClassifier.php",
        "line": 45,
        "function": "classifyFiles",
        "class": "OCA\\Recognize\\Classifiers\\Classifier",
        "type": "->"
      },
      {
        "file": "/config/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyLandmarksJob.php",
        "line": 39,
        "function": "classify",
        "class": "OCA\\Recognize\\Classifiers\\Images\\LandmarksClassifier",
        "type": "->"
      },
      {
        "file": "/config/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifierJob.php",
        "line": 67,
        "function": "classify",
        "class": "OCA\\Recognize\\BackgroundJobs\\ClassifyLandmarksJob",
        "type": "->"
      },
      {
        "file": "/config/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyLandmarksJob.php",
        "line": 31,
        "function": "runClassifier",
        "class": "OCA\\Recognize\\BackgroundJobs\\ClassifierJob",
        "type": "->"
      },
      {
        "file": "/config/www/nextcloud/lib/public/BackgroundJob/Job.php",
        "line": 78,
        "function": "run",
        "class": "OCA\\Recognize\\BackgroundJobs\\ClassifyLandmarksJob",
        "type": "->"
      },
      {
        "file": "/config/www/nextcloud/lib/public/BackgroundJob/TimedJob.php",
        "line": 103,
        "function": "start",
        "class": "OCP\\BackgroundJob\\Job",
        "type": "->"
      },
      {
        "file": "/config/www/nextcloud/lib/public/BackgroundJob/TimedJob.php",
        "line": 93,
        "function": "start",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->"
      },
      {
        "file": "/config/www/nextcloud/cron.php",
        "line": 152,
        "function": "execute",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->"
      }
    ],
    "File": "/config/www/nextcloud/apps/recognize/lib/Classifiers/Classifier.php",
    "Line": 139,
    "message": "Error while running background job (class: OCA\\Recognize\\BackgroundJobs\\ClassifyLandmarksJob, arguments: Array\n(\n    [storageId] => 1\n    [rootId] => 39166\n)\n)",
    "exception": [],
    "CustomMessage": "Error while running background job (class: OCA\\Recognize\\BackgroundJobs\\ClassifyLandmarksJob, arguments: Array\n(\n    [storageId] => 1\n    [rootId] => 39166\n)\n)"
  },
  "id": "6364d4eebdd5d"
}
```

**Comment by marcelklehr** [comment] 2022-11-07 14:32
Closing as duplicate of #370

**Closed by marcelklehr** 2022-11-07 14:32 UTC

**Comment by bugsyb** [comment] 2022-12-11 17:13
Feeling is that it might have something to do with what is described here:
https://github.com/nextcloud/recognize/issues/547
This was issue at my end and it didn't cause OOM.
