### ISSUE TITLE
Error: Call to undefined method Rubix\ML\Datasets\Labeled::features()

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/recognize#677] opened 2023-02-10 15:53 UTC
### Which version of recognize are you using?

3.5.0

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.3

### Which Operating system do you have installed?

Ubuntu 22.0.4

### Which Docker container are you using to run Nextcloud? (if applicable)

NO

### How much RAM does your server have?

23.47

### What processor Architecture does your CPU have?

X64

### Describe the Bug

N/A

### Expected Behavior

N/A

### To Reproduce

N/A

### Debug log

{"reqId":"alNJxFoae2Y5yXPE9pvS","level":3,"time":"2023-02-10T09:05:02-06:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Call to undefined method Rubix\\ML\\Datasets\\Labeled::features()","userAgent":"--","version":"25.0.3.2","exception":{"Exception":"Error","Message":"Call to undefined method Rubix\\ML\\Datasets\\Labeled::features()","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/recognize/lib/Clustering/MrdBallTree.php","line":632,"function":"split","class":"OCA\\Recognize\\Clustering\\DualTreeBall","type":"::"},{"file":"/var/www/nextcloud/apps/recognize/lib/Clustering/MstSolver.php","line":22,"function":"grow","class":"OCA\\Recognize\\Clustering\\MrdBallTree","type":"->"},{"file":"/var/www/nextcloud/apps/recognize/lib/Clustering/HDBSCAN.php","line":90,"function":"__construct","class":"OCA\\Recognize\\Clustering\\MstSolver","type":"->"},{"file":"/var/www/nextcloud/apps/recognize/lib/Service/FaceClusterAnalyzer.php","line":73,"function":"__construct","class":"OCA\\Recognize\\Clustering\\HDBSCAN","type":"->"},{"file":"/var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClusterFacesJob.php","line":39,"function":"calculateClusters","class":"OCA\\Recognize\\Service\\FaceClusterAnalyzer","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":78,"function":"run","class":"OCA\\Recognize\\BackgroundJobs\\ClusterFacesJob","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php","line":58,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php","line":48,"function":"start","class":"OCP\\BackgroundJob\\QueuedJob","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->"}],"File":"/var/www/nextcloud/apps/recognize/lib/Clustering/DualTreeBall.php","Line":107,"CustomMessage":"--"},"id":"63e667f98a574"}

**Comment by marcelklehr** [comment] 2023-02-10 16:24
duplicate of #676

**Closed by marcelklehr** 2023-02-10 16:24 UTC
Labels: bug
