### ISSUE TITLE
A lot of mistake on clusters

### ISSUE THREAD

**Issue by florealcab** [nextcloud/recognize#528] opened 2022-12-03 21:26 UTC
**Describe the bug**
I have a lot of mistake done by this app: 2 people very different (not same family, one of eauropean origin another from moroccan one) are sometime mixed on the same cluster, sometimes in the cluster I have just a cake which is not a person, or a landscape with no people... Is there a way to change some configurations to don't have these mistakes? 

I was using Face Recognition app before and I don't had these mistakes. I had just same poeple split in several clusters, like in this app but a cluster was always a same poeple. I would like to have the same behavior here.

Also, if I see the people in the photo app, I don't have always the same poeple for the same id as if I use the memories app. In the case of mixed poeple in same cluster, sometimes in the photos app I see one poeple and in the memories app it's the other one. So what is the correct poeple identified in that case ?

I used first the WASM mode as I had a warning saying "Your server does not support AVX instructions". But my server have a  Intel(R) Xeon(R) CPU D-1521 which support the AVX instruction, so I disabled WASM mode, but the behavior is the same!

Any help?

**Recognize (please complete the following information):**
 - Installed app version: [e.g. v3.1.2] 3.2.3
 - WASM mode: [e.g. Yes/No] No and Yes (two modes tested)
 - Enabled modes: [e.g. object detection, face recognition] object detection, face recognition, landmark recognition

**Server (please complete the following information):**
 - Nextcloud version: [e.g. 21.0.4] 25.0.1
 - OS: [e.g. debian] ubuntu 20.0.4
 - Docker container (if applicable): None, installed in native system
 - RAM: [e.g. 16GB] 32G
 - Processor Architecture [e.g. x86, ARM64, etc. ] x86_64

**Comment by marcelklehr** [comment] 2022-12-08 12:51
This is a duplicate of an open issue: #475

**Closed by marcelklehr** 2022-12-08 12:51 UTC
