### ISSUE TITLE
Stopped checking photos

### ISSUE THREAD

**Issue by k0stya63** [nextcloud/recognize#652] opened 2023-01-23 16:51 UTC
### Which version of recognize are you using?

3.3.6

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.3.2

### Which Operating system do you have installed?

Ubuntu server 22.04

### Which Docker container are you using to run Nextcloud? (if applicable)

-

### How much RAM does your server have?

4

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Stopped processing photos  

### Expected Behavior

I expected the process to go on as from the beginning

### To Reproduce

Didn't seem to do anything out of the ordinary, just stopped checking, waiting for some kind of line. Tried running it through `occ recognize:recrawl` but nothing happened
![err2](https://user-images.githubusercontent.com/70490566/214098201-a6bb0e76-c361-4b32-9003-414b17b01a77.png)

### Debug log

`<?php
$CONFIG = array (
  'instanceid' => '*secret*',
  'passwordsalt' => '*secret*',
  'secret' => '*secret*',
  'trusted_domains' => 
  array (
    0 => '192.168.0.201',
  ),
  'datadirectory' => '/nextcloud/data/',
  'dbtype' => 'mysql',
  'version' => '25.0.3.2',
  'overwrite.cli.url' => 'http://192.168.0.201',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextclouduser',
  'dbpassword' => '*secret*',
  'installed' => true,
  'app_install_overwrite' => 
  array (
    0 => 'occweb',
  ),
  'maintenance' => false,
);
`

**Comment by ER-EPR** [comment] 2023-01-26 15:11
my face recognition stopped two, but object recognition still working. It happened after a memory exceeding 512M error, probably caused by lacking  APCu enable in php.ini I'm not sure. I tried disabling classification and re-enable it. Last time I disable the whole plugin and re-enable it seems to work.

**Comment by MB-Finski** [comment] 2023-01-30 19:43
I've narrowed this issue down to Classifier.php (at least for me) . Seemingly if there's a failure within the Classifier.php at certain points, the face classifier que will not progress anymore. Specifically I had issues with getImageSize() (line 93) and getImagePreview() (line 241) causing uncaught errors.

Still, I think this shouldn't permanently halt the que which is a separate issue.

**Comment by shalak** [comment] 2023-02-02 02:25
@ER-EPR / @m1n3nfux does re-enabling / reinstalling makes the process start from scratch, or does it pick-up where it left off?

**Comment by ER-EPR** [comment] 2023-02-02 04:12
If you do not delete the classify cron jobs in the database, it will star where it stoped. But, if the file which caused the process to stop still exist in the jobs, probably it will stop again. You need to resolve the errors in the log first.






-------- 原始邮件 --------
发件人： Mirek ***@***.***>
日期： 2023年2月2日周四 10:25
收件人： nextcloud/recognize ***@***.***>
抄送： ER-EPR ***@***.***>, Mention ***@***.***>
主 题： Re: [nextcloud/recognize] Stopped checking photos (Issue #652)

@ER-EPR<https://github.com/ER-EPR> / @m1n3nfux<https://github.com/m1n3nfux> does re-enabling / reinstalling makes the process start from scratch, or does it pick-up where it left off?

**Comment by shalak** [comment] 2023-02-02 10:15
> You need to resolve the errors in the log first.

How can I access the recognize logs? I don't see anything in the global `Logging` menu...

**Comment by marcelklehr** [comment] 2023-02-02 12:48
> the face classifier que will not progress anymore

After a cron job raises an uncaught exception, Nextcloud will pause it for 12h, but it should restart itself automatically after that. I'll try to catch those errors.

**Comment by m1n3nfux** [comment] 2023-02-02 13:38
> @ER-EPR / @m1n3nfux does re-enabling / reinstalling makes the process start from scratch, or does it pick-up where it left off?

I remember it reprocessing every file. In the settings panel it always said "Last classification: x seconds ago" for Object recognition, but it did not add any tags for like a day. It seems like it does not check for the "Tagged by recognize v3.0.0" Tag. Though the behaviour can have other reasons too, i'm just guessing.

**Comment by marcelklehr** [comment] 2023-02-02 13:39
> I remember it reprocessing every file.

the classify command is rather dumb, indeed.

**Comment by MB-Finski** [comment] 2023-02-02 15:12
> I'll try to catch those errors.

FWIW, filtering out 0 byte files helped some but, still, corrupt files will cause an ungaught exception. My naïve attempt at catching with "\Exception" didn't help.

**Comment by marcelklehr** [comment] 2023-02-02 17:44
@MB-Finski What's the stack?

**Comment by MB-Finski** [comment] 2023-02-02 19:16
> [PHP] Error: getimagesize(): Corrupt JPEG data: 1388 extraneous bytes before marker at /var/www/nextcloud/lib/private/legacy/OC_Image.php#598 at <<closure>>
> 
>  0. <<closure>>
>     OC\Log\ErrorHandler::onError()
>  1. /var/www/nextcloud/lib/private/legacy/OC_Image.php line 598
>     getimagesize()
>  2. /var/www/nextcloud/lib/private/legacy/OC_Image.php line 665
>     OC_Image->checkImageSize()
>  3. /var/www/nextcloud/lib/private/Preview/Image.php line 52
>     OC_Image->loadFromFile()
>  4. /var/www/nextcloud/lib/private/Preview/GeneratorHelper.php line 65
>     OC\Preview\Image->getThumbnail()
>  5. /var/www/nextcloud/lib/private/Preview/Generator.php line 343
>     OC\Preview\GeneratorHelper->getThumbnail()
>  6. /var/www/nextcloud/lib/private/Preview/Generator.php line 162
>     OC\Preview\Generator->getMaxPreview()
>  7. /var/www/nextcloud/lib/private/Preview/Generator.php line 114
>     OC\Preview\Generator->generatePreviews()
>  8. /var/www/nextcloud/lib/private/PreviewManager.php line 185
>     OC\Preview\Generator->getPreview()
>  9. /var/www/nextcloud/apps/recognize/lib/Classifiers/Classifier.php line 246
>     OC\PreviewManager->getPreview()
> 10. /var/www/nextcloud/apps/recognize/lib/Classifiers/Classifier.php line 78
>     OCA\Recognize\Classifiers\Classifier->getConvertedFilePath()
> 11. /var/www/nextcloud/apps/recognize/lib/Classifiers/Images/ClusteringFaceClassifier.php line 83
>     OCA\Recognize\Classifiers\Classifier->classifyFiles()
> 12. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyFacesJob.php line 41
>     OCA\Recognize\Classifiers\Images\ClusteringFaceClassifier->classify()
> 13. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifierJob.php line 70
>     OCA\Recognize\BackgroundJobs\ClassifyFacesJob->classify()
> 14. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyFacesJob.php line 33
>     OCA\Recognize\BackgroundJobs\ClassifierJob->runClassifier()
> 15. /var/www/nextcloud/lib/public/BackgroundJob/Job.php line 78
>     OCA\Recognize\BackgroundJobs\ClassifyFacesJob->run()
> 16. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 103
>     OCP\BackgroundJob\Job->start()
> 17. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 93
>     OCP\BackgroundJob\TimedJob->start()
> 18. /var/www/nextcloud/cron.php line 152
>     OCP\BackgroundJob\TimedJob->execute()
> 
> at 
> 
> 2023-02-02T03:30:02+00:00

This is the one for a corrupt JPEG. I'm using NextcloudPi just because they have a ready-made script for setting up an LXC. It's possible/likely that their bundled version of preview generator plays a role here..?

**Comment by marcelklehr** [comment] 2023-02-02 20:17
686572c3a9ea359738c2880ec5ae6d9285d6f8ed should fix that by suppressing the E_WARNING

**Comment by marcelklehr** [comment] 2023-03-19 16:48
Closing this for now as the surface issue was fixed. If this comes up again, let me know.

**Closed by marcelklehr** 2023-03-19 16:48 UTC
Labels: bug
